services:
  mysql-nullbank:
    image: mysql:8.0
    container_name: db_nullbank
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Root
      MYSQL_DATABASE: Equipe567258
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRoot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nullbank-frontend:
    build: .
    container_name: nullbank_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      mysql-nullbank:
        condition: service_healthy

volumes:
  db_data:
